### ISSUE TITLE
[Website] bad code pls dont use ai generated

### ISSUE THREAD

**Issue by losowyLP** [ByteOverload/bugtracker#2]
### About the bug

pixel stoåp using ai generated css code it literally unreadable and my eyes are in severe pain

### Steps to reproduce

just dont use ai ffs

### Expected behavour

get good at css

### My environment

your mom and brave web brower best web browser

### Screenshots

![1280x720](https://user-images.githubusercontent.com/77402345/123626184-d6d08c00-d810-11eb-9035-7aa637786f7f.jpg)

### Additional context

dont ai generate

**Comment by WhosPix3l** [comment]
wtf

**Comment by WhosPix3l** [comment]
your mom

**Comment by losowyLP** [comment]
@WhosPix3l i think you should look further into this

**Comment by WhosPix3l** [comment]
yeah i think i should

**Comment by WhosPix3l** [comment]
your mom

**Comment by WhosPix3l** [comment]
you literally fixed it yourself lmao

**Comment by losowyLP** [comment]
oh hey thats right lmfao
