### ISSUE TITLE
[Website] Nav buttons not centred vertically

### ISSUE THREAD

**Issue by losowyLP** [ByteOverload/bugtracker#4]
### About the bug
Navigation buttons aren't centered vertically on navbar

### Steps to reproduce
Just look at the navbar lol

### Expected behavour
I expected the text to be vertically centered

### My environment
All of them lmao

### Additional context
@WhosPix3l if I'm sleeping while you are reading this then please fix it

**Comment by WhosPix3l** [comment]
fixed i need you to center the main logo now lol i cant figure it out
